name: french_conjugation_learn
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  easy_localization: 3.0.1
  auto_route: 5.0.1
  flutter_bloc: 8.1.1
  hooked_bloc: 1.2.0
  equatable: 2.0.5
  json_serializable: 6.4.1
  freezed: 2.1.0+1
  freezed_annotation: 2.1.0
  json_annotation: 4.7.0
  get_it: 7.2.0
  injectable: 1.5.3
  dio: 4.0.6
  retrofit: 3.0.2
  shared_preferences: 2.0.15
  encrypted_shared_preferences: 3.0.1
  flutter_svg: 1.1.5
  flutter_hooks: 0.18.5+1
  cached_network_image: 3.2.2
  theme_tailor_annotation: 1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1
  mocktail: 0.3.0
  bloc_test: 9.1.0
  injectable_generator: 1.5.4
  build_runner: 2.2.1
  auto_route_generator: 5.0.2
  retrofit_generator: 4.1.2
  pretty_dio_logger: 1.2.0-beta-1
  theme_tailor: 1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/fonts/